### PR TITLE
Update BoxItem.java

### PR DESCRIPTION
**Pull request by trb727**
Fix typo in getParent() comment

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @trb727, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by trb727** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @trb727 has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by gcurtis** [comment]
Thanks!

**Pull request merged**
