### PR TITLE
Allow changing the request HTTP connection object from a RequestInterceptor

### PR DESCRIPTION
**Pull request by dorfire**
For example, to trust self-signed certificates.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @dorfire, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by dorfire** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @dorfire has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by nddipiazza** [comment]
+1 from me. i also had to do something similar to prevent duplicate As-User headers

**Pull request closed without merging**
