### PR TITLE
Fixed #183 by changing the event collection object from HashSet to Li…

### LINKED ISSUE #183: Order of box events gets changed because the SDK uses HashSet for BoxEvents
Order of the events from box become random after they are added into the HashSet. See below code from EventLog.java
```
this.chunkSize = json.get("chunk_size").asInt();
this.set = new HashSet<BoxEvent>(this.chunkSize);
JsonArray entries = json.get("entries").asArray();
```
If we use LinkedHashSet then it will maintain the insertion order

It is a small change and I can submit a pull request for it.

### PR DESCRIPTION
**Pull request by itsmanishagarwal**
Changed the collection object used to hold the BoxEvent from HashSet to LinkedHasSet. This will preserve the order of the events.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @itsmanishagarwal, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by itsmanishagarwal** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @itsmanishagarwal has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by gcurtis** [comment]
Thanks for the fix!

**Pull request merged**
