### PR TITLE
Ability to set connect and read timeout globally.

### PR DESCRIPTION
**Pull request by sbellan**
Currently there is no easy way to set the socket timeout's for the Http url connection, since the attributes are on the BoxAPIRequest and BoxAPIRequest's are created in many places internally.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @sbellan, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by sbellan** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @sbellan has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by iamharish** [comment]
Thanks for the pull request @sbellan

**Comment by fjollberg** [comment]
I'm looking forward for this ending up in a release near me. Very much needed.

**Comment by iamharish** [comment]
Released. Should be in maven repo soon.

**Pull request merged**
