### PR TITLE
Add new attributes to BoxGroup.Info: description, provenance, externa…

### PR DESCRIPTION
**Pull request by maurercw**
…l_sync_identifier, invitability_level, member_viewability_level

Add new createGroup method that takes the new attributes.

Addresses issue #219

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @maurercw has signed the CLA. Thanks for the pull request!

**Comment by tarrencev** [comment]
Looks good to me 👍 

@gcurtis @codyebberson

**Comment by maurercw** [comment]
Bah, my IDE likes to change around my import statements on it's own.  I'll fix...

**Comment by tarrencev** [comment]
Awesome, thanks for the PR!

**Pull request merged**
