### PR TITLE
Deprecated enums still being used

### LINKED ISSUE #931: Deprecated enums still being used
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
The current version of BoxSDK has deprecated Type in BoxEvent.java but it is atleast being used in EventLog.java.

### Versions Used
Java SDK: 2.57.0
Java: 11

### PR DESCRIPTION
**Pull request by mittal-umang**
Fixes #931

### CODE REVIEW

**Comment by antusus** [comment]
Hi @mittal-umang,

Sorry for late response. I can see the problem with duplicating methods having varargs arguments. 
I'm a big fan of request objects. It allow us to define required and optional parameters. And I would go this way in this scenario. In fact I'm currently working on this method as I want to prepare SDK to work with new stream of events. Here is the method definition:

`public static EventLog getEnterpriseEvents(BoxAPIConnection api, EnterpriseEventsRequest request)`

Where `EnterpriseEventsRequest` will contain all the parameters like after, before, limit, etc. This new method will be using new enum values. Example of usage:

```
EnterpriseEventsRequest request = new EnterpriseEventsRequest()
    .after(after)
    .before(before)
    .limit(limit)
    .position(position)
    .types(eventTypes);
EventLog.getEnterpriseEvents(api, request);
```

I will post PR link most likely next week.

**Comment by antusus** [comment]
Pull request that fixes the problem with deprecated enums being used: https://github.com/box/box-java-sdk/pull/934

**Comment by mittal-umang** [comment]
Hi Kamil,

Does this PR fix the issue mentioned earlier. I'm currently not available
to look at this completely.

I would really appreciate if you could let me know if i still need to fix
the code i pushed in the earlier PR?

Regards,
Umang Mittal
+1 (404) 952-5883

**Comment by antusus** [comment]
No you do not need to merge your PR. I went with completely different approach.
Old methods are now marked as deprecated and the new method uses only new BoxEvent.EventType.
This should solve #931 issue.

**Comment by antusus** [comment]
The issue should be resolved with release of [2.58.0](https://github.com/box/box-java-sdk/releases/tag/v2.58.0)

**Pull request closed without merging**
