### PR TITLE
Implement Get By Path for files and folders

### PR DESCRIPTION
**Pull request by mattwiller**

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @mattwiller has signed the CLA. Thanks for the pull request!

**Comment by iamharish** [comment]
Do you want to add integration tests as well?

**Comment by gsaslis** [comment]
Any idea when this could get merged?

I came to the java sdk from your ruby sdk (where this is available) and I found it really odd this is not yet available (porting the app to java was not as straightforward). 

p.s. thanks @mattwiller !

**Comment by mattwiller** [comment]
@gsaslis That API is not totally finalized yet — we're waiting to implement it in the SDKs until we're sure there won't be any more changes to it.  It should hopefully be released sometime in the next month!

**Pull request closed without merging**
