### PR TITLE
Allow content streaming to box through outputstream.

### PR DESCRIPTION
**Pull request by gajarajkalburgi**
Feature Request : Allow content streaming to box through outputstream.

Closes : #666

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @gajarajkalburgi has signed the CLA. Thanks for the pull request!

**Comment by carycheng** [comment]
@gajarajkalburgi,

Thank you for the pull request, we really appreciate it! We will review this in the morning.

It looks like one of your tests is failing on Java 7 which we need the SDK to be compatible with.

If you wouldn't mind fixing that up, that would be great, thanks!

```
/home/travis/build/box/box-java-sdk/src/test/java/com/box/sdk/BoxFolderTest.java:150: error: static interface method invocations are not supported in -source 1.7 final Stream<String> fileContent = Stream.of("Test file");

**Comment by gajarajkalburgi** [comment]
@carycheng 

Thank you for your quick response.
I fixed PR and it's now success build. 👍

**Comment by carycheng** [comment]
Hey @gajarajkalburgi, 

This all looks great! It's been merged and will go out with our next release, thank you for the PR, we really appreciate it!

**Comment by gajarajkalburgi** [comment]
@carycheng , 

Thank you so much for your review and approval.
Is thre any plan for releasing this feature ?

**Comment by carycheng** [comment]
Hey @gajarajkalburgi, 

Your feature went out with our release today v2.25.0, please take a look, thank you!

https://search.maven.org/artifact/com.box/box-java-sdk/2.25.0/jar

**Pull request merged**
