### PR TITLE
Fixing BoxDeveloperEditionAPIConnection - decryptPrivateKey() - PEMParser returns PrivateKeyInfo already - Invalid cast #470

### PR DESCRIPTION
**Pull request by henrykuijpers**
Pull request for #470

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @henrykuijpers, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by henrykuijpers** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @henrykuijpers has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by iamharish** [comment]
Thanks for the PR @henrykuijpers

**Comment by henrykuijpers** [comment]
Welcome. :)

**Pull request merged**
