### PR TITLE
Fixes #872

### LINKED ISSUE #872: Need ability to provide configurable permissions when managing Group Memeberships
### Is your feature request related to a problem? Please describe.
The Box Group Membership object does not have the ability to specify configurable permissions when adding members to the group and when updating  existing group membership.

 "configurable_permissions": {
    "can_run_reports": true
  }

### Describe the solution you'd like
Add a Permission enum in Box Group Membership and a create and update method to provide the configurable permissions in the BoxGroupMembership.java

### Describe alternatives you've considered
REST APIs

### Additional context
The default in the admin console in the box web app when adding members to a group as admins gives all permissions to the group members. Its odd that default group admin permissions are not restricted and there is no UI while adding the members as admins to select their group membership permissions. There is a not so obvious gear icon next to each member that allows one to change the configurable permissions after the member has been added in the web UI but since its not so obvious it has resulted in group admins with full privileges in 100s of our box groups partly due to user experience of the web app and partly due to lack of knowledge of our admins of how powerful the default group admins can be in Box.  We need to bring security permissions in compliance and since this change needs to happen to 100s of groups, we will have to use now APIs to restrict the group admin members permissions.

### PR DESCRIPTION
**Pull request by rjainrohit**

### CODE REVIEW

**Comment by swfree** [comment]
Hi @rjainrohit,

Thanks for this PR! Can you add a test for your change? For example, you could test updating the membership here: https://github.com/box/box-java-sdk/blob/main/src/test/java/com/box/sdk/BoxGroupMembershipTest.java#L100

Thanks,
@swfree

**Comment by mwwoda** [comment]
Hi @rjainrohit 

Thank you for the contribution! I updated your PR with tests. @swfree can you look at this once more?

Thanks,
@mwwoda

**Review by swfree — APPROVED** [review]

**Comment by mwwoda** [comment]
Hi @rjainrohit 

This PR is already reviewed and ready to be merged. Last thing we need from you is to sign the CLA.

Thanks,
@mwwoda

**Comment by sujaygarlanka** [comment]
@rjainrohit We added your change through our PR (#897) because the CLA for this PR was not signed. Thank you for your contribution. We really appreciate it!

**Pull request closed without merging**
