### PR TITLE
Update the file `search.md`

### PR DESCRIPTION
**Pull request by LouisWayne**
- Typo fix: `BoxItems.Info` -> `BoxItem.Info`

Fixes typo

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @LouisWayne, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by LouisWayne** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @LouisWayne has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by carycheng** [comment]
Thanks @LouisWayne!

**Pull request merged**
