### PR TITLE
Fix for #761 (Properly throw exceptions for setMetadata on Files and Folders)

### PR DESCRIPTION
**Pull request by kmcroft13**
Fixes issue #761

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @kmcroft13, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by kmcroft13** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @kmcroft13 has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by kmcroft13** [comment]
There is also an issue with the test for BoxFolderTest.testSetMetadata

**Pull request merged**
